Wastewater proxy merge
USEPA/GEPA pull request #29
Opened 2024-12-16 21:49 UTC by ccoxen

Pull completed wastewater proxy script in with V3. This script writes all of the industrial wastewater proxies and the nonseptic domestic proxy.

2024-12-17 15:27 UTC, ccoxen commented
I went through the updated script to address merge conflicts with the existing script, it should be ready for merge now.

2025-01-15 16:08 UTC, nkruskamp reviewed
Looks good Chris. Some of the helper functions would be great to pull out and put in utils and I'd like to clean up the geospatial operations to use geopandas with meter based distances.

2025-01-15 23:08 UTC, nkruskamp requested changes
This is a complex one. Let'see how much we can extract common functions and get the outputs wrapped into a set of functions with defined input and output files for clarify.

2025-01-15 23:13 UTC, nkruskamp commented on gch4i/proxy_processing/task_wastewater_proxy.py
>  # %%
Let's get ahead of John's code review an add a header for this file.

2025-01-24 21:41 UTC, ccoxen commented on gch4i/proxy_processing/task_wastewater_proxy.py
>  # %%
Done!

2025-01-24 21:56 UTC, ccoxen commented on gch4i/proxy_processing/task_wastewater_proxy.py
> +def geocode_address(df, address_column):
did this in my recent PR for peatlands. sorry if this confused things!

2025-01-24 21:58 UTC, ccoxen commented on gch4i/proxy_processing/task_wastewater_proxy.py
> +                dist = np.sqrt((ghgrp_row['latitude'] - echo_row['latitude'])**2 +
This sounds great but I'm not sure how to implement that change given my limited understanding of geospatial transformations in python. If we have time to talk through this some time I'd love to better understand what you mean and how to integrate those changes here.

2025-01-27 17:08 UTC, ccoxen commented on gch4i/proxy_processing/task_wastewater_proxy.py
>  def convert_state_names_to_codes(df, state_column):
His is similar. In the interest of moving through all of my recent PRs before we need to submit this to EPA, I'll leave here for now and I will consolodate after?

2025-01-27 17:11 UTC, ccoxen reviewed
I made a few changes to address your comments and left responses on all of your comments. I will circle back to the geospatial changes to integrate established geopandas functions and work on integrating existing utility functions (like John's state abbreviation one) after we get through this final delivery push.

2025-01-27 17:14 UTC, merged