Add anaeriobic digestion proxy script
USEPA/GEPA pull request #30
Opened 2024-12-19 21:47 UTC by ccoxen

Add anaeriobic digestion script to the proxy scripts to process the proxy file for anaerobic digesters

2025-01-15 17:23 UTC, nkruskamp commented on gch4i/proxy_processing/task_anaerobic_digestion.py
> +WRRF = 23587 / total_SCFM # 23,587 SCFM is from WRRF
Are these values fixed by facility type? The code below looks to do the the allocation of inventory emissions to the facilities and then normalizes those. In this case think that allocation step isn't necessary. I may be missing something here. Let's talk it through.

2025-01-15 17:25 UTC, nkruskamp commented on gch4i/proxy_processing/task_anaerobic_digestion.py
> +anaerobic_digestion_emi = pd.read_csv(emi_data_dir_path / "anaerobic_digestion_emi.csv")
Let's wrap the entirety of the inputs files and output proxy file into a function so it is clear which files are being used. For the emi file see the other comment on if we need it here or not since allocation happens in the next step.

2025-01-15 17:37 UTC, nkruskamp requested changes
Chris, looking good. My question is if we have fixed values from the biogas report, I think those should be assigned and normalized by facility type, and we don't need to use the emissions inventory values here, since the allocation by relative amount happens in the next step.

Can we wrap everything into a single function so that it's clear the full list of input and output files for this proxy?

2025-01-27 21:11 UTC, ccoxen commented on gch4i/proxy_processing/task_anaerobic_digestion.py
> +anaerobic_digestion_emi = pd.read_csv(emi_data_dir_path / "anaerobic_digestion_emi.csv")
Done!

2025-01-27 21:29 UTC, ccoxen commented on gch4i/proxy_processing/task_anaerobic_digestion.py
> +WRRF = 23587 / total_SCFM # 23,587 SCFM is from WRRF
Yes these values are fixed by facility type. I understand what you're suggesting but I'm having trouble wrapping my brain around what this would look like. Let's chat and I'm glad to integrate into the script!

2025-01-27 21:32 UTC, ccoxen reviewed
I've got this set up to run in pytask but I haven't changed any code to address your normalize emi comment. Let's talk through that and I can better understand what that change would look like. Otherwise ready to merge.

2025-02-18 21:51 UTC, ccoxen reviewed
Updated code to produce relative emissions by state and fixed misc pytask related code issues

2025-03-18 14:47 UTC, merged